###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

users:
  authelia:
    displayname: "Test User"
    password: "$argon2id$v=19$m=1048576,t=1,p=8$WGo2dW1IYzBYZi9INHFrZg$oy4aymXxjNYWXwmFAiHJrCkxT75cCUTrkr3nnL5xXl4" # Password is 'authelia'
    email: authelia@authelia.com
    groups:
      - admins
      - dev
      - torrent
