version: '2'

services:
  freshrss:
    image: 'lscr.io/linuxserver/freshrss:${FRESHRSS_IMAGE_VERSION:-latest}'
    container_name: 'freshrss'
    environment:
      PUID: '${FRESHRSS_PUID:-1000}'
      PGID: '${FRESHRSS_PGID:-1000}'
      TZ: '${TZ:-Europe/Paris}'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/']
      interval: '30s'
      timeout: '10s'
      retries: 3
      start_period: '60s'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.freshrss.rule: 'Host(`freshrss.${SITE:-localhost}`)'
      traefik.http.routers.freshrss.entrypoints: 'websecure'
      traefik.http.routers.freshrss.tls.certresolver: 'letsencrypt'
      traefik.http.routers.freshrss.middlewares: 'basic_auth@docker'
      traefik.http.services.freshrss.loadbalancer.server.port: 80
    networks:
      - 'srv'
    restart: 'unless-stopped'
    volumes:
      - './data:/config'
